# no "version" key

x-common-env: &common_env
  env_file:
    - .env
  extra_hosts:
    - "host.docker.internal:host-gateway"
  environment:
    HOME: /tmp
    NPM_CONFIG_CACHE: /tmp/.npm

x-common-mounts: &common_mounts
  working_dir: /workspace
  volumes:
    # mount project source
    - ./:/workspace
    # move cached node_modules here
    - /opt/resources/node_mod_cache/data_acq:/workspace/node_modules
    - /opt/run-logs/data_acquisition:/opt/run-logs/data_acquisition  # <-- added for logs

services:
  app:
    image: node:lts
    <<: [*common_env, *common_mounts]

  app_tools:
    build:
      context: .
      dockerfile: docker/Dockerfile.runtime
    <<: [*common_env, *common_mounts]
