INSERT INTO
    config.acquisition(
        system_id,
        host_ip,
        mmb_ip,
        protocal,
        debian_server_path,
        credentials_group,
        acquisition_script,
        run_group,
        host,
        user_id,
        acqu_point,
        last_updated_by
    )
VALUES
    (
        'SME20288',
        '20.55.232.226',
        NULL,
        NULL,
        '/home/staging/hhm_data_acquisition/files/SME20288_temp',
        NULL,
        'althea_server_pull.sh',
        1,
        NULL,
        'mattteixeira',
        'althea_vm',
        'matt.teixeira@avantehs.com'
    );